version: "3.1"

services:
  db:
    image: postgres:16.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_feed_bot
      PGDATA: /var/lib/postgresql/data/
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: andrei.kozel@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80

volumes:
  db:
